### ISSUE TITLE
[AWS] Look up IP addresses within EC2 instances via IMDSv2 instead

### ISSUE THREAD

**Issue by kelvintaywl** [CircleCI-Public/server-terraform#189]
## Background

Currently, our [_nomad_startup.sh.tpl_ script (for AWS EC2)](https://github.com/CircleCI-Public/server-terraform/blob/main/nomad-aws/template/nomad-startup.sh.tpl#L68-L79) looks up the public and private IPv4 addresses via the IMDSv1 API.

## Proposal

Use the [IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) API instead to fetch the public and private IP addresses.

This requires a small change in the sequence of API calls needed.
See 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instancedata-data-retrieval.html#instance-metadata-retrieval-examples

## Reasons

- AWS recommends using IMDSv2 over IMDSv1 if possible
- Depending on the region, EC2 instance type and etc, the provisioned EC2 instances may have IMDSv2 marked as required (i.e., IMDSv1 is not usable)
   * a customer hit this issue, and had to update the script to use IMDSv2 instead.
- Administrators may have disabled IMDSv1 overall in the AWS account (e.g., via [System Manager](https://docs.aws.amazon.com/systems-manager-automation-runbooks/latest/userguide/automation-aws-enforce-ec2-imdsv2.html))

## Additional

- https://aws.amazon.com/blogs/security/get-the-full-benefits-of-imdsv2-and-disable-imdsv1-across-your-aws-infrastructure/

**Comment by ryanwohara** [comment]
This is being addressed in https://github.com/CircleCI-Public/server-terraform/pull/190
